### ISSUE TITLE
Update docs for user properties

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog-node#40]
I think the docs on https://posthog.com/docs/libraries/node needs to be updated,  seems that properties interface has been updated

interface CommonParamsInterfacePropertiesProp {
  [key: string]: string | number | Array<any | { [key: string]: string | number }>
}
![image](https://user-images.githubusercontent.com/1727427/123623281-86a3fa80-d80d-11eb-9e08-65a1a527fddc.png)

cc @yakkomajuri this was sent to me by a user, any thoughts? Seems weird that this code example doesn't work

**Comment by yakkomajuri** [comment]
Actually the types should be updated. 

Since the beginning our types haven't allowed another object as a value here, `$set` didn't change anything, just made it visible.

Original commit for these prop types:

https://github.com/PostHog/posthog-node/commit/f1179750d5640f50b6341cec17f170023519d408#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8
