### ISSUE TITLE
The type definitions are missing `callback`

### ISSUE THREAD

**Issue by Alkasai** [PostHog/posthog-node#78]
Looking at the source code (e.g. `identify` [method](https://github.com/PostHog/posthog-node/blob/master/index.js#L121)), many methods have a `callback`, but in the type definitions the `callback` is [missing](https://github.com/PostHog/posthog-node/blob/master/index.d.ts#L54).
If someone wanted to await for these methods' callback to be called (not sure if this is the best practice), they would get a compile error.

These methods also `return this`, but in the type definitions they return `void`.

Is this intended? Can we update the type definitions with the all the optional prams and correct return types?

**Comment by benjackwhite** [comment]
This repo has been superseded by our new common JS approach ([see here](https://github.com/PostHog/posthog-js-lite/tree/master/posthog-node)) so that code is a bit out of date. You are correct however that the old definitions were incorrectly typed.

Since version 2.x the callback params are removed.
